### ISSUE TITLE
Impossible to run python d2v.py

### ISSUE THREAD

**Issue by Petkomat** [hadijomaa/dataset2vec#3]
Running `python d2v.py` results in the following error:

```
Traceback (most recent call last):
  File "C:/Users/matejp/git/nsu/vaje03/dataset2vec-master/d2v.py", line 55, in <module>
    normalized_dataset         = Dataset(configuration,rootdir,use_valid=True)
  File "C:\Users\matejp\git\nsu\vaje03\dataset2vec-master\dataset.py", line 59, in __init__
    self.minmax        = configuration['minmax']
KeyError: 'minmax'
```

**Comment by hadijomaa** [comment]
Thank you for your feedback. There was indeed a minor bug in the code. 
Please refer to the updated version. For any other problems, please open
another issue.
Hadi
